import Head from 'next/head';
import { useEffect, useState } from 'react';
import { Table } from '../components/table';

export function handleData(data) {
  let total;
  const tasks = data
    ?.map((task) => {
      if (task.TAREFA === 'Total') {
        total = {
          vencido: task.VENCIDO,
          d0: task.D0,
          d1: task.D1,
          d2: task.D2,
          d3: task.D3,
          total: task.TOTAL
        };
        return undefined;
      }
      const details = task.DRILLDOWN.map((detail) => {
        return {
          instancia: detail.INSTANCIA,
          status: detail.STATUS,
          protocolo: detail.PROTOCOLO,
          regua: detail.REGUA,
          inicio: detail.inicio,
          sla: detail.SLA,
          tipo: detail.TIPO_SOLICITACAO,
          operador: detail.operador
        };
      });

      return {
        tarefa: task.TAREFA,
        vencido: task.VENCIDO,
        d0: task.D0,
        d1: task.D1,
        d2: task.D2,
        d3: task.D3,
        total: task.TOTAL,
        details: details
      };
    })
    .filter(Boolean);

  return {
    tasks,
    total
  };
}

export default function Home() {
  const [tasks, setTasks] = useState([]);
  const [total, setTotal] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    setIsLoading(true);
    fetch('https://ico-fullstack-test.herokuapp.com/v1/histograma')
      .then((res) => res.json())
      .then((data) => {
        const { tasks, total } = handleData(data);
        setTasks(tasks);
        setTotal(total);
        setIsLoading(false);
      });
  }, []);

  return (
    <div className="flex m-3">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Table tasks={tasks} total={total} isLoading={isLoading} />
    </div>
  );
}
